name: fastAPI and mflow model with Docker

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: kubernetes_tutorial/tutorial-classifier
          registry: docker.io
          directory: fastAPI
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
