name: fastAPI and mflow model with Docker

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./fastAPI
          push: true
          tags: marcc70/kubernetes_tutorial:latest, marcc70/kubernetes_tutorial:${{ github.run_number }}
        
